<?xml version="1.0" encoding="utf-8"?><Database Name="QLBanDoChoi" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=NINH-PC\SQLEXPRESS;Initial Catalog=QLBanDoChoi;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLBanDoChoiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChatLieu" Member="ChatLieus">
    <Type Name="ChatLieu">
      <Column Name="MaCL" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenCL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ChatLieu_DoChoi" Member="DoChois" ThisKey="MaCL" OtherKey="MaCL" Type="DoChoi" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietDonHang" Member="ChiTietDonHangs">
    <Type Name="ChiTietDonHang">
      <Column Name="MaDH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDC" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="DoChoi_ChiTietDonHang" Member="DoChoi" ThisKey="MaDC" OtherKey="MaDC" Type="DoChoi" IsForeignKey="true" />
      <Association Name="DonHang_ChiTietDonHang" Member="DonHang" ThisKey="MaDH" OtherKey="MaDH" Type="DonHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DoChoi" Member="DoChois">
    <Type Name="DoChoi">
      <Column Name="MaDC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="AnhBia" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SoLuongTon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaXX" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLoai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DoChoi_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="MaDC" OtherKey="MaDC" Type="ChiTietDonHang" />
      <Association Name="ChatLieu_DoChoi" Member="ChatLieu" ThisKey="MaCL" OtherKey="MaCL" Type="ChatLieu" IsForeignKey="true" />
      <Association Name="Loai_DoChoi" Member="Loai" ThisKey="MaLoai" OtherKey="MaLoai" Type="Loai" IsForeignKey="true" />
      <Association Name="ThuongHieu_DoChoi" Member="ThuongHieu" ThisKey="MaTH" OtherKey="MaTH" Type="ThuongHieu" IsForeignKey="true" />
      <Association Name="XuatXu_DoChoi" Member="XuatXu" ThisKey="MaXX" OtherKey="MaXX" Type="XuatXu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonHang" Member="DonHangs">
    <Type Name="DonHang">
      <Column Name="MaDH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DaThanhToan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayGiao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TinhTrangGiao" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DonHang_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="MaDH" OtherKey="MaDH" Type="ChiTietDonHang" />
      <Association Name="KhachHang_DonHang" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="KhachHang_DonHang" Member="DonHangs" ThisKey="MaKH" OtherKey="MaKH" Type="DonHang" />
    </Type>
  </Table>
  <Table Name="dbo.Loai" Member="Loais">
    <Type Name="Loai">
      <Column Name="MaLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Loai_DoChoi" Member="DoChois" ThisKey="MaLoai" OtherKey="MaLoai" Type="DoChoi" />
    </Type>
  </Table>
  <Table Name="dbo.ThuongHieu" Member="ThuongHieus">
    <Type Name="ThuongHieu">
      <Column Name="MaTH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ThuongHieu_DoChoi" Member="DoChois" ThisKey="MaTH" OtherKey="MaTH" Type="DoChoi" />
    </Type>
  </Table>
  <Table Name="dbo.XuatXu" Member="XuatXus">
    <Type Name="XuatXu">
      <Column Name="MaXX" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenXX" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="XuatXu_DoChoi" Member="DoChois" ThisKey="MaXX" OtherKey="MaXX" Type="DoChoi" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="UserAdmin" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PassAdmin" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Hoten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>